apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: dotnetcore
  name: dotnet-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: dotnetcore
    spec:
      containers:
      - image: ramesh8800/dotnetcore:$BUILD_NUMBER
        name: dotnetcore
        ports:
        - name: dotnet
          containerPort: 80      
---
# Node Port Service
apiVersion: v1
kind: Service
metadata:
  labels:
    name: dotnetcore
  name: dotnetcore
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: dotnetcore
