apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-dep
spec:
  selector:
    matchLabels:
      app: jenkins
  replicas: 1
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
        - name: jenkins
          image: ramesh8800/dotnetcore:$BUILD_NUMBER
          imagePullPolicy: IfNotPresent
          ports:
            - name: http-port
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: jenkins
